const PERMISSIONS = [
  ["dashboard.view", "dashboard", "view", "View dashboard"],
  ["dashboard.export", "dashboard", "export", "Export dashboard"],
  ["users.view", "users", "view", "View users"],
  ["users.create", "users", "create", "Create users"],
  ["users.edit", "users", "edit", "Edit users"],
  ["users.activate", "users", "activate", "Activate or deactivate users"],
  ["users.reset_password", "users", "reset_password", "Reset user passwords"],
  ["users.manage_roles", "users", "manage_roles", "Assign user roles"],
  ["roles.view", "roles", "view", "View roles"],
  ["roles.manage", "roles", "manage", "Manage roles"],
  ["permissions.view", "permissions", "view", "View permissions"],
  ["permissions.manage", "permissions", "manage", "Manage permissions"],
  ["audit_logs.view", "audit_logs", "view", "View audit logs"],
  ["audit_logs.export", "audit_logs", "export", "Export audit logs"],
  ["stock.view", "stock", "view", "View stock"],
  ["stock.create", "stock", "create", "Create stock"],
  ["stock.edit", "stock", "edit", "Edit stock"],
  ["stock.delete", "stock", "delete", "Delete stock"],
  ["stock.export", "stock", "export", "Export stock"],
  ["stock.reconcile", "stock", "reconcile", "Reconcile stock"],
  ["stock.scan", "stock", "scan", "Scan purchase stock"],
  ["suppliers.view", "suppliers", "view", "View suppliers"],
  ["suppliers.create", "suppliers", "create", "Create suppliers"],
  ["suppliers.edit", "suppliers", "edit", "Edit suppliers"],
  ["suppliers.delete", "suppliers", "delete", "Delete suppliers"],
  ["suppliers.export", "suppliers", "export", "Export suppliers"],
  ["departments.view", "departments", "view", "View departments"],
  ["departments.create", "departments", "create", "Create departments"],
  ["departments.edit", "departments", "edit", "Edit departments"],
  ["departments.delete", "departments", "delete", "Delete departments"],
  ["purchase_orders.view", "purchase_orders", "view", "View purchase orders"],
  ["purchase_orders.create", "purchase_orders", "create", "Create purchase orders"],
  ["purchase_orders.edit", "purchase_orders", "edit", "Edit purchase orders"],
  ["purchase_orders.delete", "purchase_orders", "delete", "Delete purchase orders"],
  ["purchase_orders.approve", "purchase_orders", "approve", "Approve purchase orders"],
  ["purchase_orders.export", "purchase_orders", "export", "Export purchase orders"],
  ["grn.view", "grn", "view", "View goods receipts"],
  ["grn.create", "grn", "create", "Create goods receipts"],
  ["grn.delete", "grn", "delete", "Delete goods receipts"],
  ["grn.scan", "grn", "scan", "Scan goods receipts"],
  ["reorder_points.view", "reorder_points", "view", "View reorder points"],
  ["reorder_points.create", "reorder_points", "create", "Create reorder points"],
  ["reorder_points.edit", "reorder_points", "edit", "Edit reorder points"],
  ["reorder_points.delete", "reorder_points", "delete", "Delete reorder points"],
  ["reorder_points.approve", "reorder_points", "approve", "Approve reorder actions"],
  ["reconciliation.view", "reconciliation", "view", "View reconciliation"],
  ["reconciliation.create", "reconciliation", "create", "Create reconciliation"],
  ["reconciliation.approve", "reconciliation", "approve", "Approve reconciliation"],
  ["transfers.view", "transfers", "view", "View transfers"],
  ["transfers.create", "transfers", "create", "Create transfers"],
  ["transfers.approve", "transfers", "approve", "Approve transfers"],
  ["transfers.delete", "transfers", "delete", "Delete transfers"],
  ["menu.view", "menu", "view", "View menu plans"],
  ["menu.create", "menu", "create", "Create menu plans"],
  ["menu.edit", "menu", "edit", "Edit menu plans"],
  ["menu.delete", "menu", "delete", "Delete menu plans"],
  ["recipes.view", "recipes", "view", "View recipes"],
  ["recipes.create", "recipes", "create", "Create recipes"],
  ["recipes.edit", "recipes", "edit", "Edit recipes"],
  ["recipes.delete", "recipes", "delete", "Delete recipes"],
  ["indents.view", "indents", "view", "View indents"],
  ["indents.create", "indents", "create", "Create indents"],
  ["indents.edit", "indents", "edit", "Edit indents"],
  ["indents.delete", "indents", "delete", "Delete indents"],
  ["indents.approve", "indents", "approve", "Approve indents"],
  ["indents.export", "indents", "export", "Export indents"],
  ["issuances.view", "issuances", "view", "View issuances"],
  ["issuances.create", "issuances", "create", "Create issuances"],
  ["issuances.scan", "issuances", "scan", "Scan issuance forms"],
  ["issuances.export", "issuances", "export", "Export issuances"],
  ["issuances.delete", "issuances", "delete", "Delete issuances"],
  ["production.view", "production", "view", "View production"],
  ["production.create", "production", "create", "Create production"],
  ["production.edit", "production", "edit", "Edit production"],
  ["production.delete", "production", "delete", "Delete production"],
  ["leftovers.view", "leftovers", "view", "View leftovers"],
  ["leftovers.create", "leftovers", "create", "Create leftovers"],
  ["leftovers.edit", "leftovers", "edit", "Edit leftovers"],
  ["leftovers.delete", "leftovers", "delete", "Delete leftovers"],
  ["waste_analytics.view", "waste_analytics", "view", "View waste analytics"],
  ["waste_analytics.export", "waste_analytics", "export", "Export waste analytics"],
  ["chef_stats.view", "chef_stats", "view", "View chef statistics"],
  ["chef_stats.export", "chef_stats", "export", "Export chef statistics"],
  ["search.view", "search", "view", "Use global search"],
  ["scan.indent", "scan", "indent", "Scan indent forms"],
  ["scan.purchase", "scan", "purchase", "Scan purchase documents"],
  ["scan.text", "scan", "text", "Parse text"],
  ["approved_delivery.scan", "approved_delivery", "scan", "Scan approved delivery"],
  ["approved_delivery.commit", "approved_delivery", "commit", "Commit approved delivery"],
  ["settings.view", "settings", "view", "View settings"],
  ["settings.manage", "settings", "manage", "Manage settings"],
].map(([key, resource, action, label]) => ({ key, resource, action, label }));

const all = PERMISSIONS.map((p) => p.key);

const ROLE_PERMISSION_KEYS = {
  admin: all,
  manager: all.filter((key) => ![
    "users.view", "users.create", "users.edit", "users.activate", "users.reset_password", "users.manage_roles",
    "roles.view", "roles.manage", "permissions.view", "permissions.manage", "audit_logs.export",
    "settings.view", "settings.manage",
    "suppliers.delete", "departments.create", "departments.edit", "departments.delete", "stock.delete",
    "purchase_orders.delete", "grn.delete", "transfers.delete", "menu.delete", "recipes.delete",
    "production.delete", "leftovers.delete", "issuances.delete", "indents.delete",
  ].includes(key)),
  store_manager: [
    "stock.view", "stock.create", "stock.edit", "stock.delete", "stock.export", "stock.reconcile", "stock.scan",
    "issuances.view", "issuances.create", "issuances.scan", "issuances.export",
    "scan.indent", "scan.purchase", "scan.text",
  ],
  chef: [
    "recipes.view", "recipes.create", "recipes.edit", "recipes.delete",
    "indents.view", "indents.create", "indents.edit", "indents.delete", "indents.approve",
    "production.view", "production.create", "production.edit", "production.delete",
    "leftovers.view", "leftovers.create", "leftovers.edit", "leftovers.delete",
    "waste_analytics.view", "waste_analytics.export",
    "scan.indent", "scan.text",
  ],
  employee: [
    "dashboard.view", "departments.view", "transfers.view", "transfers.create", "menu.view",
    "recipes.view", "indents.view", "indents.create", "production.view", "production.create",
    "leftovers.view", "leftovers.create", "chef_stats.view", "search.view",
  ],
};

module.exports = { PERMISSIONS, ROLE_PERMISSION_KEYS };
